const titles = [
  'Aspect Ratio',
  // 'Container',
  'Columns',
  'Break After',
  'Break Before',
  'Break Inside',
  'Box Decoration Break',
  'Box Sizing',
  'Display',
  'Floats',
  'Clear',
  'Isolation',
  'Object Fit',
  'Object Position',
  'Overflow',
  'Overscroll Behavior',
  'Position',
  'Top / Right / Bottom / Left',
  'Visibility',
  'Z-Index',
  'Flex Basis',
  'Flex Direction',
  'Flex Wrap',
  'Flex',
  'Flex Grow',
  'Flex Shrink',
  'Order',
  'Grid Template Columns',
  'Grid Column Start / End',
  'Grid Template Rows',
  'Grid Row Start / End',
  'Grid Auto Flow',
  'Grid Auto Columns',
  'Grid Auto Rows',
  'Gap',
  'Justify Content',
  'Justify Items',
  'Justify Self',
  'Align Content',
  'Align Items',
  'Align Self',
  'Place Content',
  'Place Items',
  'Place Self',
  'Padding',
  'Margin',
  'Space Between',
  'Width',
  'Min-Width',
  'Max-Width',
  'Height',
  'Min-Height',
  'Max-Height',
  'Font Family',
  'Font Size',
  'Font Smoothing',
  'Font Style',
  'Font Weight',
  'Font Variant Numeric',
  'Letter Spacing',
  'Line Height',
  'List Style Type',
  'List Style Position',
  'Text Align',
  'Text Color',
  'Text Decoration',
  'Text Decoration Color',
  'Text Decoration Style',
  'Text Decoration Thickness',
  'Text Underline Offset',
  'Text Transform',
  'Text Overflow',
  'Text Indent',
  'Vertical Align',
  'Whitespace',
  'Word Break',
  'Content',
  'Background Attachment',
  'Background Clip',
  'Background Color',
  'Background Origin',
  'Background Position',
  'Background Repeat',
  'Background Size',
  'Background Image',
  'Gradient Color Stops',
  'Border Radius',
  'Border Width',
  'Border Color',
  'Border Style',
  'Divide Width',
  'Divide Color',
  'Divide Style',
  'Outline Width',
  'Outline Color',
  'Outline Style',
  'Outline Offset',
  'Ring Width',
  'Ring Color',
  'Ring Offset Width',
  'Ring Offset Color',
  'Box Shadow',
  'Box Shadow Color',
  'Opacity',
  'Mix Blend Mode',
  'Background Blend Mode',
  'Blur',
  'Brightness',
  'Contrast',
  'Drop Shadow',
  'Grayscale',
  'Hue Rotate',
  'Invert',
  'Saturate',
  'Sepia',
  'Backdrop Blur',
  'Backdrop Brightness',
  'Backdrop Contrast',
  'Backdrop Grayscale',
  'Backdrop Hue Rotate',
  'Backdrop Invert',
  'Backdrop Opacity',
  'Backdrop Saturate',
  'Backdrop Sepia',
  'Border Collapse',
  'Border Spacing',
  'Table Layout',
  'Transition Property',
  'Transition Duration',
  'Transition Timing Function',
  'Transition Delay',
  'Animation',
  'Scale',
  'Rotate',
  'Translate',
  'Skew',
  'Transform Origin',
  'Accent Color',
  'Appearance',
  'Cursor',
  'Caret Color',
  'Pointer Events',
  'Resize',
  'Scroll Behavior',
  'Scroll Margin',
  'Scroll Padding',
  'Scroll Snap Align',
  'Scroll Snap Stop',
  'Scroll Snap Type',
  'Touch Action',
  'User Select',
  'Will Change',
  'Fill',
  'Stroke',
  'Stroke Width',
  'Screen Readers',
]

export default titles
